// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WingsAir_API.Models;

public partial class Aeropuerto_WingsAirContext : DbContext
{
    public Aeropuerto_WingsAirContext(DbContextOptions<Aeropuerto_WingsAirContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Aeropuertos> Aeropuertos { get; set; }

    public virtual DbSet<Aviones> Aviones { get; set; }

    public virtual DbSet<Pilotos> Pilotos { get; set; }

    public virtual DbSet<Vuelos> Vuelos { get; set; }

    public virtual DbSet<VuelosPorEstatus> VuelosPorEstatus { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Aeropuertos>(entity =>
        {
            entity.HasKey(e => e.id_aeropuerto).HasName("PK__Aeropuer__207E2F0385737E54");
        });

        modelBuilder.Entity<Aviones>(entity =>
        {
            entity.HasKey(e => e.id_avion).HasName("PK__Aviones__66D8A4F317712D59");

            entity.Property(e => e.horas_de_vuelo).HasDefaultValue(0);
        });

        modelBuilder.Entity<Pilotos>(entity =>
        {
            entity.HasKey(e => e.id_piloto).HasName("PK__Pilotos__93ED52353709F57C");

            entity.Property(e => e.horas_de_vuelo).HasDefaultValue(0);
            entity.Property(e => e.sexo).IsFixedLength();
        });

        modelBuilder.Entity<Vuelos>(entity =>
        {
            entity.HasKey(e => e.id_vuelo).HasName("PK__Vuelos__CA179BA2497F3548");

            entity.ToTable(tb => tb.HasTrigger("ActualizarHorasVuelo"));

            entity.Property(e => e.estatus).HasDefaultValue("En Espera");

            entity.HasOne(d => d.id_avionNavigation).WithMany(p => p.Vuelos).HasConstraintName("FK_Vuelos_Avion");

            entity.HasOne(d => d.id_destinoNavigation).WithMany(p => p.Vuelosid_destinoNavigation).HasConstraintName("FK_Vuelos_Destino");

            entity.HasOne(d => d.id_origenNavigation).WithMany(p => p.Vuelosid_origenNavigation).HasConstraintName("FK_Vuelos_Origen");

            entity.HasOne(d => d.id_pilotoNavigation).WithMany(p => p.Vuelos).HasConstraintName("FK_Vuelos_Piloto");
        });

        modelBuilder.Entity<VuelosPorEstatus>(entity =>
        {
            entity.ToView("VuelosPorEstatus");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}