// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WingsAir_API.Models;

[Index("codigo_piloto", Name = "UQ__Pilotos__F01BC1A4917AA072", IsUnique = true)]
public partial class Pilotos
{
    [Key]
    public int id_piloto { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string codigo_piloto { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string nombre_completo { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string sexo { get; set; }

    public int? horas_de_vuelo { get; set; }

    [InverseProperty("id_pilotoNavigation")]
    public virtual ICollection<Vuelos> Vuelos { get; set; } = new List<Vuelos>();
}