// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WingsAir_API.Models;

[Microsoft.EntityFrameworkCore.Index("codigo_vuelo", Name = "UQ__Vuelos__E819276FCBDFBA51", IsUnique = true)]
public partial class Vuelos
{
    [Key]
    public int id_vuelo { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string codigo_vuelo { get; set; }

    public int? id_origen { get; set; }

    public int? id_destino { get; set; }

    public int? id_piloto { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_hora { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string estatus { get; set; }

    public int? horas_vuelo { get; set; }

    public int? id_avion { get; set; }

    [ForeignKey("id_avion")]
    [InverseProperty("Vuelos")]
    public virtual Aviones id_avionNavigation { get; set; }

    [ForeignKey("id_destino")]
    [InverseProperty("Vuelosid_destinoNavigation")]
    public virtual Aeropuertos id_destinoNavigation { get; set; }

    [ForeignKey("id_origen")]
    [InverseProperty("Vuelosid_origenNavigation")]
    public virtual Aeropuertos id_origenNavigation { get; set; }

    [ForeignKey("id_piloto")]
    [InverseProperty("Vuelos")]
    public virtual Pilotos id_pilotoNavigation { get; set; }
}