// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WingsAir_API.Models;

[Keyless]
public partial class VuelosPorEstatus
{
    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string codigo_vuelo { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string tipo_avion { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string piloto { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string origen { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string destino { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_hora { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string estatus { get; set; }
}